pipeline {
	agent any
	stages {

	       stage('Lint HTML') {
		  steps {
			   sh 'tidy -q -e ./Deployment-pipeline/*.html'
			}
		}
		
		stage('Build Docker Image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker build -t ahmedemad2051/capstone ./Deployment-pipeline/
					'''
				}
			}
		}

		stage('Push Image To Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
						docker push ahmedemad2051/capstone
					'''
				}
			}
		}

		stage('Set current kubectl context') {
			steps {
				withAWS(region:'us-east-1', credentials:'capstone_cred') {
					sh '''
						kubectl config use-context arn:aws:eks:us-east-1:534135317400:cluster/capstonecluster
					'''
				}
			}
		}

		stage('Deploy blue container') {
			steps {
				withAWS(region:'us-east-1', credentials:'capstone_cred') {
					sh '''
						kubectl apply -f ./Deployment-pipeline/blue-controller.json
					'''
				}
			}
		}

		stage('Deploy green container') {
			steps {
				withAWS(region:'us-east-1', credentials:'capstone_cred') {
					sh '''
						kubectl apply -f ./Deployment-pipeline/green-controller.json
					'''
				}
			}
		}

		stage('Create the service in the cluster, redirect to blue') {
			steps {
				withAWS(region:'us-east-1', credentials:'capstone_cred') {
					sh '''
						kubectl apply -f ./Deployment-pipeline/blue-service.json
					'''
				}
			}
		}

		stage('Wait user approve') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('Create the service in the cluster, redirect to green') {
			steps {
				withAWS(region:'us-east-1', credentials:'capstone_cred') {
					sh '''
						kubectl apply -f ./Deployment-pipeline/green-service.json
					'''
				}
			}
		}

	}
}
